spring:
  data:
    redis:
      host: localhost

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
    livereload:
      enabled: true

  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop

logging:
  level:
    root: INFO
    com.andrewstsai.instashare: DEBUG
    org.springframework.web: DEBUG
    org.springframework.messaging: DEBUG